SelfLanguage/Controllers/CreateController.cs
/*
 * By: voidotexe
 * https://www.github.com/voidotexe
*/

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SelfLanguage.Models;
using SelfLanguage.Services;
using System;
using System.Threading.Tasks;

namespace SelfLanguage.Controllers
{
    [Authorize]
    public class CreateController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly IVideoService _videoService;
        private readonly ITranscriptionService _transcriptionService;
        private readonly ISubtitleService _subtitleService;

        public CreateController(UserManager<User> userManager, IVideoService videoService, ITranscriptionService transcriptionService, ISubtitleService subtitleService)
        {
            _userManager = userManager;
            
            _videoService = videoService;
            _transcriptionService = transcriptionService;
            _subtitleService = subtitleService;
        }

        [HttpGet]
        public IActionResult Video()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Video(VideoViewModel videoViewModel)
        {
            videoViewModel.CreatedBy = _userManager.GetUserId(User);
            videoViewModel.CreatedAt = DateTime.Now;

            var video = new Video(videoViewModel.Title, videoViewModel.Link, videoViewModel.VideoLanguage, videoViewModel.Difficulty, videoViewModel.CreatedBy, videoViewModel.CreatedAt);
            string videoResponse = await _videoService.PostVideoApi(video);
            int videoId = Convert.ToInt32(videoResponse);

            var transcription = new Transcription(videoId, videoViewModel.TranscriptionContent, videoViewModel.CreatedBy, videoViewModel.CreatedAt);
            await _transcriptionService.CallTranscriptionApi(transcription);

            var subtitle = new Subtitle(videoId, videoViewModel.SubtitleContent, videoViewModel.SubtitleLanguage, videoViewModel.CreatedBy, videoViewModel.CreatedAt);
            await _subtitleService.CallSubtitleApi(subtitle);

            return View(videoViewModel);
        }
    }
}

SelfLanguage/Controllers/FavoriteVideoController.cs
/*
 * By: voidotexe
 * https://www.github.com/voidotexe
*/

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SelfLanguage.Models;
using SelfLanguage.Services;
using System.Threading.Tasks;

namespace SelfLanguage.Controllers
{
    [Authorize]
    public class FavoriteVideoController : Controller
    {
        private readonly ILogger<FavoriteVideoController> _logger;
        private readonly IFavoriteVideoService _favoriteVideoService;
        private readonly UserManager<User> _userManager;

        public FavoriteVideoController(ILogger<FavoriteVideoController> logger, IFavoriteVideoService favoriteVideoService, UserManager<User> userManager)
        {
            _logger = logger;
            _favoriteVideoService = favoriteVideoService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await _favoriteVideoService.ReadByUserIdApi(_userManager.GetUserId(User));

            return View(_favoriteVideoService.FavoriteVideos);
        }
    }
}

SelfLanguage/Views/Shared/_Layout.cshtml
@*
 * By: voidotexe
 * https://www.github.com/voidotexe
*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Self Language</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Self Language</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Create" asp-action="Video">Criar vídeo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="FavoriteVideo" asp-action="Index">Vídeos favoritos</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SelfLanguage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>