SelfLanguage/Controllers/HomeController.cs
/*
 * By: voidotexe
 * https://www.github.com/voidotexe
*/

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SelfLanguage.Models;
using SelfLanguage.Services;
using System.Diagnostics;
using System.Threading.Tasks;

namespace SelfLanguage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IVideoService _videoService;

        public HomeController(ILogger<HomeController> logger, IVideoService videoService)
        {
            _logger = logger;
            _videoService = videoService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await _videoService.GetVideoApi();

            return View(_videoService.Videos);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SelfLanguage/Controllers/VideoController.cs
/*
 * By: voidotexe
 * https://www.github.com/voidotexe
*/

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SelfLanguage.Models;
using SelfLanguage.Services;
using System.Threading.Tasks;

namespace SelfLanguage.Controllers
{
    public class VideoController : Controller
    {
        private readonly ILogger<VideoController> _logger;
        private readonly IVideoService _videoService;
        private readonly UserManager<User> _userManager;

        public VideoController(ILogger<VideoController> logger, IVideoService videoService, UserManager<User> userManager)
        {
            _logger = logger;
            _videoService = videoService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string link)
        {
            await _videoService.GetSingleVideoApi(link);

            await _videoService.GetCheckUserHasSingleFavoriteVideoApi(_videoService.Video.VideoId, _userManager.GetUserId(User));

            return View(_videoService.Video);
        }
    }
}

SelfLanguage/Views/Home/Index.cshtml
@*
 * By: voidotexe
 * https://www.github.com/voidotexe
*@

@model IEnumerable<VideoViewModel>

@{
    ViewData["Title"] = "Início";
}

@foreach (var m in Model)
{
    string link = m.Link.Replace("https://www.youtube.com/watch?v=", "");

    <div class="card">
        <div class="card-body">
            <img src="@m.VideoImage"/>
            <a asp-action="Index" asp-controller="Video" asp-route-link="@link">
                <h4 class="card-title">@m.Title</h4>
            </a>
            <i class="fa-solid fa-globe"></i> @m.VideoLanguage
            <br />
            <i class="fa-solid fa-brain"></i> @m.Difficulty
            <br />
            <i class="fa-solid fa-user"></i> @m.CreatedBy
            <br />
            <i class="fa-solid fa-clock"></i> @m.CreatedAt
        </div>
    </div>
    <br>
}